config/routes.rb
Rails.application.routes.draw do
  resources :alerts
  resources :alert_types
  resources :groups
  resources :users

  root to: 'alerts#index'

  get 'twilio/send_sms', to: 'twilio#send_sms'
  post 'twilio/send_sms', to: 'twilio#send_sms'

  get 'twilio/receive_sms', to: 'twilio#receive_sms'
  post 'twilio/receive_sms', to: 'twilio#receive_sms'

  get 'twilio/check_messages', to: 'twilio#check_messages', defaults: {format: "json"}

end

app/controllers/alert_types_controller.rb
class AlertTypesController < ApplicationController
  before_action :set_alert_type, only: [:show, :edit, :update, :destroy]

  # GET /alert_types
  # GET /alert_types.json
  def index
    @alert_types = AlertType.all
  end

  # GET /alert_types/1
  # GET /alert_types/1.json
  def show
  end

  # GET /alert_types/new
  def new
    @alert_type = AlertType.new
  end

  # GET /alert_types/1/edit
  def edit
  end

  # POST /alert_types
  # POST /alert_types.json
  def create
    @alert_type = AlertType.new(alert_type_params)

    respond_to do |format|
      if @alert_type.save
        format.html { redirect_to @alert_type, notice: 'Alert type was successfully created.' }
        format.json { render :show, status: :created, location: @alert_type }
      else
        format.html { render :new }
        format.json { render json: @alert_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alert_types/1
  # PATCH/PUT /alert_types/1.json
  def update
    respond_to do |format|
      if @alert_type.update(alert_type_params)
        format.html { redirect_to @alert_type, notice: 'Alert type was successfully updated.' }
        format.json { render :show, status: :ok, location: @alert_type }
      else
        format.html { render :edit }
        format.json { render json: @alert_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alert_types/1
  # DELETE /alert_types/1.json
  def destroy
    @alert_type.destroy
    respond_to do |format|
      format.html { redirect_to alert_types_url, notice: 'Alert type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert_type
      @alert_type = AlertType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_type_params
      params.require(:alert_type).permit(:name)
    end
end

app/helpers/alert_types_helper.rb
module AlertTypesHelper
end

app/views/alert_types/_form.html.erb
<%= form_for(@alert_type) do |f| %>
  <% if @alert_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert_type.errors.count, "error") %> prohibited this alert_type from being saved:</h2>

      <ul>
      <% @alert_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alert_types/edit.html.erb
<h1>Editing Alert Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @alert_type %> |
<%= link_to 'Back', alert_types_path %>

app/views/alert_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alert Types</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alert_types.each do |alert_type| %>
      <tr>
        <td><%= alert_type.type %></td>
        <td><%= link_to 'Show', alert_type %></td>
        <td><%= link_to 'Edit', edit_alert_type_path(alert_type) %></td>
        <td><%= link_to 'Destroy', alert_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alert type', new_alert_type_path %>

app/views/alert_types/new.html.erb
<h1>New Alert Type</h1>

<%= render 'form' %>

<%= link_to 'Back', alert_types_path %>

app/views/alert_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @alert_type.name %>
</p>

<%= link_to 'Edit', edit_alert_type_path(@alert_type) %> |
<%= link_to 'Back', alert_types_path %>